# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/share/c/github/cpp-case

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/share/c/github/cpp-case

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/share/c/github/cpp-case/CMakeFiles /data/share/c/github/cpp-case/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/share/c/github/cpp-case/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cppcase

# Build rule for target.
Cppcase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Cppcase
.PHONY : Cppcase

# fast build rule for target.
Cppcase/fast:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/build
.PHONY : Cppcase/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/main.cpp.s
.PHONY : main.cpp.s

others/well_number.o: others/well_number.cpp.o

.PHONY : others/well_number.o

# target to build an object file
others/well_number.cpp.o:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/others/well_number.cpp.o
.PHONY : others/well_number.cpp.o

others/well_number.i: others/well_number.cpp.i

.PHONY : others/well_number.i

# target to preprocess a source file
others/well_number.cpp.i:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/others/well_number.cpp.i
.PHONY : others/well_number.cpp.i

others/well_number.s: others/well_number.cpp.s

.PHONY : others/well_number.s

# target to generate assembly for a file
others/well_number.cpp.s:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/others/well_number.cpp.s
.PHONY : others/well_number.cpp.s

stl/vector.o: stl/vector.cpp.o

.PHONY : stl/vector.o

# target to build an object file
stl/vector.cpp.o:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/stl/vector.cpp.o
.PHONY : stl/vector.cpp.o

stl/vector.i: stl/vector.cpp.i

.PHONY : stl/vector.i

# target to preprocess a source file
stl/vector.cpp.i:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/stl/vector.cpp.i
.PHONY : stl/vector.cpp.i

stl/vector.s: stl/vector.cpp.s

.PHONY : stl/vector.s

# target to generate assembly for a file
stl/vector.cpp.s:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/stl/vector.cpp.s
.PHONY : stl/vector.cpp.s

template/template.o: template/template.cpp.o

.PHONY : template/template.o

# target to build an object file
template/template.cpp.o:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/template/template.cpp.o
.PHONY : template/template.cpp.o

template/template.i: template/template.cpp.i

.PHONY : template/template.i

# target to preprocess a source file
template/template.cpp.i:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/template/template.cpp.i
.PHONY : template/template.cpp.i

template/template.s: template/template.cpp.s

.PHONY : template/template.s

# target to generate assembly for a file
template/template.cpp.s:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/template/template.cpp.s
.PHONY : template/template.cpp.s

threads/joinable.o: threads/joinable.cpp.o

.PHONY : threads/joinable.o

# target to build an object file
threads/joinable.cpp.o:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/threads/joinable.cpp.o
.PHONY : threads/joinable.cpp.o

threads/joinable.i: threads/joinable.cpp.i

.PHONY : threads/joinable.i

# target to preprocess a source file
threads/joinable.cpp.i:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/threads/joinable.cpp.i
.PHONY : threads/joinable.cpp.i

threads/joinable.s: threads/joinable.cpp.s

.PHONY : threads/joinable.s

# target to generate assembly for a file
threads/joinable.cpp.s:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/threads/joinable.cpp.s
.PHONY : threads/joinable.cpp.s

threads/thread.o: threads/thread.cpp.o

.PHONY : threads/thread.o

# target to build an object file
threads/thread.cpp.o:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/threads/thread.cpp.o
.PHONY : threads/thread.cpp.o

threads/thread.i: threads/thread.cpp.i

.PHONY : threads/thread.i

# target to preprocess a source file
threads/thread.cpp.i:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/threads/thread.cpp.i
.PHONY : threads/thread.cpp.i

threads/thread.s: threads/thread.cpp.s

.PHONY : threads/thread.s

# target to generate assembly for a file
threads/thread.cpp.s:
	$(MAKE) -f CMakeFiles/Cppcase.dir/build.make CMakeFiles/Cppcase.dir/threads/thread.cpp.s
.PHONY : threads/thread.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Cppcase"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... others/well_number.o"
	@echo "... others/well_number.i"
	@echo "... others/well_number.s"
	@echo "... stl/vector.o"
	@echo "... stl/vector.i"
	@echo "... stl/vector.s"
	@echo "... template/template.o"
	@echo "... template/template.i"
	@echo "... template/template.s"
	@echo "... threads/joinable.o"
	@echo "... threads/joinable.i"
	@echo "... threads/joinable.s"
	@echo "... threads/thread.o"
	@echo "... threads/thread.i"
	@echo "... threads/thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

